services:
  api:
    container_name: api-reserva-de-projetores
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -sf http://127.0.0.1:8000/ || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  db:
    container_name: db-reserva-de-projetores
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fastapi
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fastapi -d fastapi"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: