[tool.ruff]
line-length = 79
extend-exclude = ['migrations']

[tool.ruff.lint]
preview = true
select = ['I', 'F', 'E', 'W', 'PL', 'PT']
ignore = ['E501']  # Ignora o erro de linha muito longa

[tool.ruff.format]
preview = true
quote-style = 'single'

[tool.pytest.ini_options]
pythonpath = "."
addopts = '-p no:warnings'

[tool.coverage.run]
omit = [
    "*/tests/*",
    "*/migrations/*",
    "*/__pycache__/*",
    "app/*",
    "*/conftest.py",
    "*/__init__.py",
]

[tool.taskipy.tasks]
lint = 'ruff check .'
format = 'ruff check --fix && ruff format .'
run = 'uvicorn app.main:app --reload --port 8000'
test = 'pytest -s -x --cov=. -vv'
post_test = 'coverage html'